background = 0xFFFDF6E3
base = 0xFFF7F0DD
text = 0xFF657B83
alternate_base = 0xFFEEE8D5
bright_text = 0xFF586E75
accent = 0xFF268BD2
link_text = 0xFF268BD2
accent_secondary = 0xFF2AA198
font_family = "IBM Plex Mono"
font_family_monospace = "monospace"
font_size = 13
small_font_size = 10
rounding_large = 0
rounding_small = 0
