# theme: solarized-light
background #FDF6E3
foreground #657B83
cursor #268BD2
cursor_text_color #FDF6E3
selection_foreground #657B83
selection_background #EEE8D5
active_tab_background #F7F0DD
active_tab_foreground #657B83
inactive_tab_background #EEE8D5
inactive_tab_foreground #839496
background_opacity 0.90
color0 #073642
color1 #DC322F
color2 #859900
color3 #B58900
color4 #268BD2
color5 #D33682
color6 #2AA198
color7 #EEE8D5
color8 #586E75
color9 #CB4B16
color10 #859900
color11 #B58900
color12 #268BD2
color13 #6C71C4
color14 #2AA198
color15 #FDF6E3
